# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testSpace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testSpace

  pod 'Firebase/Messaging'
  
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'testSpaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'testSpace-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testSpace-tvOS

  target 'testSpace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
